### ISSUE TITLE
Beta does not contain .nrm file

### ISSUE THREAD

**Issue by TSEG6** [LT-Schmiddy/mm-forms-use-more-items#1]
title self explanatory imo
![image](https://github.com/user-attachments/assets/a8d3410a-7d97-4924-beba-8661a3e3c03e)

**Comment by LT-Schmiddy** [comment]
... How... How did I miss that?

I'll reupload in just a little bit

**Comment by LT-Schmiddy** [comment]
Fixed now.

**Comment by TSEG6** [comment]
Things happen lol
